const defaultData = {
  coupleName: "Sarah & James",
  date: "September 14, 2025",
  venueName: "The Grand Rosewood Estate",
  venueCity: "Tuscany, Italy",
  story: "We met on a rainy Tuesday at a bookshop neither of us meant to walk into. He reached for the same book, I dropped my coffee — and somehow that became our favourite story to tell. Five years later, we're still reaching for the same things.",
  storyChapter2: "Our first date was a long walk through the old city streets, talking about everything and nothing at once. By the end of that evening, we both knew something rare had begun. The years since have been filled with adventures big and small — road trips at dawn, quiet Sunday mornings, and a thousand moments that reminded us how lucky we are to have found each other.",
  storyChapter3: "When James got down on one knee at our favourite little café — the one where we'd had our third date — Sarah's answer was yes before he'd even finished the question. We can't wait to celebrate this next chapter with the people we love most.",
  welcomeMessage: "With joyful hearts we invite you to celebrate with us",
  ceremony: "4:30 PM — Garden Chapel",
  reception: "7:00 PM — The Grand Hall",
  dresscode: "Black Tie Optional",
  rsvpDeadline: "August 1, 2025",
  footerNote: "We can't wait to celebrate with you ♡",
  groom: "James",
  bride: "Sarah",
  groomBio: "James grew up in Edinburgh, Scotland. A passionate architect by day and amateur chef by night, he believes the best things in life are handcrafted — including this wedding.",
  brideBio: "Sarah, originally from Cape Town, South Africa, is a writer and landscape photographer who finds beauty in the overlooked corners of the world. She found the most beautiful corner of all in James.",
  howWeMet: "We met on a rainy Tuesday at a bookshop neither of us meant to walk into.",
  firstDate: "Our first date was a long walk through the old city streets, talking about everything and nothing.",
  proposal: "James proposed at our favourite little café over espresso and a shared slice of tiramisu.",
  photos: new Array(20).fill(null),
  coverPhoto: null,
  accentColor: "#b5867a",
  secondaryColor: "#e8d5cc",
  bgColor: "#fffaf8",
  textColor: "#3d2c2c",
  template: 0,
};

export default defaultData;